{
    "vulnerability_insights": [
        {
            "114": {
                "metadata": {
                    "timestamp": "2025-08-27T19:42:46.484580+05:30",
                    "package": "certifi",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "certifi",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 5 - Production/Stable",
                                "Intended Audience :: Developers",
                                "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
                                "Natural Language :: English",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3 :: Only",
                                "Programming Language :: Python :: 3.10",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.13",
                                "Programming Language :: Python :: 3.7",
                                "Programming Language :: Python :: 3.8",
                                "Programming Language :: Python :: 3.9"
                            ]
                        }
                    ]
                },
                "developer_view": [],
                "tech_leader_view": {
                    "total_vulnerabilities": 0,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 0,
                        "medium": 0,
                        "low": 0
                    }
                }
            },
            "115": {
                "metadata": {
                    "timestamp": "2025-08-27T19:42:48.976895+05:30",
                    "package": "charset_normalizer",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "charset_normalizer",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 5 - Production/Stable",
                                "Intended Audience :: Developers",
                                "Operating System :: OS Independent",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3 :: Only",
                                "Programming Language :: Python :: 3.10",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.13",
                                "Programming Language :: Python :: 3.14",
                                "Programming Language :: Python :: 3.7",
                                "Programming Language :: Python :: 3.8",
                                "Programming Language :: Python :: 3.9",
                                "Programming Language :: Python :: Implementation :: CPython",
                                "Programming Language :: Python :: Implementation :: PyPy",
                                "Topic :: Text Processing :: Linguistic",
                                "Topic :: Utilities",
                                "Typing :: Typed"
                            ]
                        }
                    ]
                },
                "developer_view": [],
                "tech_leader_view": {
                    "total_vulnerabilities": 0,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 0,
                        "medium": 0,
                        "low": 0
                    }
                }
            },
            "116": {
                "metadata": {
                    "timestamp": "2025-08-27T19:42:51.089241+05:30",
                    "package": "idna",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "idna",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 5 - Production/Stable",
                                "Intended Audience :: Developers",
                                "Intended Audience :: System Administrators",
                                "License :: OSI Approved :: BSD License",
                                "Operating System :: OS Independent",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3 :: Only",
                                "Programming Language :: Python :: 3.10",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.13",
                                "Programming Language :: Python :: 3.6",
                                "Programming Language :: Python :: 3.7",
                                "Programming Language :: Python :: 3.8",
                                "Programming Language :: Python :: 3.9",
                                "Programming Language :: Python :: Implementation :: CPython",
                                "Programming Language :: Python :: Implementation :: PyPy",
                                "Topic :: Internet :: Name Service (DNS)",
                                "Topic :: Software Development :: Libraries :: Python Modules",
                                "Topic :: Utilities"
                            ]
                        }
                    ]
                },
                "developer_view": [
                    {
                        "vulnerability_id": "GHSA-jjg7-2v4v-x38h",
                        "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
                        "affected_components": [
                            "idna"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "3.7"
                        ],
                        "impact": "### Impact\nA specially crafted argument to the `idna",
                        "remediation_steps": "Upgrade to 3.7",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
                            },
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3651"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/kjd/idna"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/idna/PYSEC-2024-60.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2024-60",
                        "summary": "",
                        "affected_components": [
                            "idna"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                            "level": "High"
                        },
                        "fixed_versions": [
                            "1d365e17e10d72d0b7876316fc7b9ca0eebdd38d"
                        ],
                        "impact": "A vulnerability was identified in the kjd/idna library, specifically within the `idna",
                        "remediation_steps": "Upgrade to 1d365e17e10d72d0b7876316fc7b9ca0eebdd38d",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d"
                            }
                        ]
                    }
                ],
                "tech_leader_view": {
                    "total_vulnerabilities": 2,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 1,
                        "medium": 1,
                        "low": 0
                    }
                }
            },
            "117": {
                "metadata": {
                    "timestamp": "2025-08-27T19:42:54.723291+05:30",
                    "package": "numpy",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "numpy",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 5 - Production/Stable",
                                "Intended Audience :: Developers",
                                "Intended Audience :: Science/Research",
                                "License :: OSI Approved :: BSD License",
                                "Operating System :: MacOS",
                                "Operating System :: Microsoft :: Windows",
                                "Operating System :: POSIX",
                                "Operating System :: Unix",
                                "Programming Language :: C",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3 :: Only",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.13",
                                "Programming Language :: Python :: 3.14",
                                "Programming Language :: Python :: Implementation :: CPython",
                                "Topic :: Scientific/Engineering",
                                "Topic :: Software Development",
                                "Typing :: Typed"
                            ]
                        }
                    ]
                },
                "developer_view": [
                    {
                        "vulnerability_id": "GHSA-2fc2-6r4j-p65h",
                        "summary": "Numpy arbitrary file write via symlink attack",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.8.1"
                        ],
                        "impact": "(1) core/tests/test_memmap",
                        "remediation_steps": "Upgrade to 1.8.1",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-1859"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/pull/4262"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009"
                            },
                            {
                                "type": "advisory",
                                "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91317"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-2fc2-6r4j-p65h"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2018-34.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://web.archive.org/web/20200228165750/http://www.securityfocus.com/bid/65440"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-5545-2q6w-2gh6",
                        "summary": "NumPy NULL Pointer Dereference",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                            "level": "High"
                        },
                        "fixed_versions": [
                            "1.19"
                        ],
                        "impact": "Null Pointer Dereference vulnerability exists in numpy",
                        "remediation_steps": "Upgrade to 1.19",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41495"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/19038"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-5545-2q6w-2gh6"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-856.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-9fq2-x9r6-wfmf",
                        "summary": "Numpy Deserialization of Untrusted Data",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                            "level": "Critical"
                        },
                        "fixed_versions": [],
                        "impact": "** DISPUTED **   An issue was discovered in NumPy 1",
                        "remediation_steps": "No fix available",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-6446"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/12759"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/pull/12889"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2019-108.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
                            },
                            {
                                "type": "advisory",
                                "url": "https://web.archive.org/web/20210124234613/https://www.securityfocus.com/bid/106670"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-cw6w-4rcx-xphc",
                        "summary": "Arbitrary file write in NumPy",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.8.1"
                        ],
                        "impact": "__init__",
                        "remediation_steps": "Upgrade to 1.8.1",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-1858"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/pull/4262"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009"
                            },
                            {
                                "type": "advisory",
                                "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91318"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-cw6w-4rcx-xphc"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2018-33.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.securityfocus.com/bid/65441"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-f7c7-j99h-c22f",
                        "summary": "Buffer Copy without Checking Size of Input in NumPy",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.19"
                        ],
                        "impact": "Buffer overflow in the array_from_pyobj function of fortranobject",
                        "remediation_steps": "Upgrade to 1.19",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41496"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/19000"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-fpfv-jqm9-f5jm",
                        "summary": "Incorrect Comparison in NumPy",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.22"
                        ],
                        "impact": "Incomplete string comparison in the numpy",
                        "remediation_steps": "Upgrade to 1.22",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34141"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/18993"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-frgw-fgh6-9g52",
                        "summary": "Numpy missing input validation",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                            "level": "High"
                        },
                        "fixed_versions": [
                            "1.13.3"
                        ],
                        "impact": "The numpy",
                        "remediation_steps": "Upgrade to 1.13.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-12852"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-frgw-fgh6-9g52"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/releases/tag/v1.13.3"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2017-1.yaml"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2017-1",
                        "summary": "",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.13.3"
                        ],
                        "impact": "The numpy",
                        "remediation_steps": "Upgrade to 1.13.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-frgw-fgh6-9g52"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2018-33",
                        "summary": "",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                        ],
                        "impact": "__init__",
                        "remediation_steps": "Upgrade to 0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/pull/4262"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst"
                            },
                            {
                                "type": "advisory",
                                "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91318"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.securityfocus.com/bid/65441"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-cw6w-4rcx-xphc"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2018-34",
                        "summary": "",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                        ],
                        "impact": "(1) core/tests/test_memmap",
                        "remediation_steps": "Upgrade to 0bb46c1448b0d3f5453d5182a17ea7ac5854ee15",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/pull/4262"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst"
                            },
                            {
                                "type": "advisory",
                                "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/91317"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1062009"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.securityfocus.com/bid/65440"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2014/02/08/3"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-2fc2-6r4j-p65h"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2019-108",
                        "summary": "",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.16.1"
                        ],
                        "impact": "** DISPUTED **   An issue was discovered in NumPy 1",
                        "remediation_steps": "Upgrade to 1.16.1",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/12759"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.securityfocus.com/bid/106670"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2021-856",
                        "summary": "",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.19.1"
                        ],
                        "impact": "Null Pointer Dereference vulnerability exists in numpy",
                        "remediation_steps": "Upgrade to 1.19.1",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/19038"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-5545-2q6w-2gh6"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2021-857",
                        "summary": "",
                        "affected_components": [
                            "numpy"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.19.0"
                        ],
                        "impact": "Buffer overflow in the array_from_pyobj function of fortranobject",
                        "remediation_steps": "Upgrade to 1.19.0",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/numpy/numpy/issues/19000"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-f7c7-j99h-c22f"
                            }
                        ]
                    }
                ],
                "tech_leader_view": {
                    "total_vulnerabilities": 13,
                    "severity_breakdown": {
                        "critical": 1,
                        "high": 2,
                        "medium": 4,
                        "low": 0
                    }
                }
            },
            "118": {
                "metadata": {
                    "timestamp": "2025-08-27T19:42:58.958713+05:30",
                    "package": "pandas",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "pandas",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 5 - Production/Stable",
                                "Environment :: Console",
                                "Intended Audience :: Science/Research",
                                "License :: OSI Approved :: BSD License",
                                "Operating System :: OS Independent",
                                "Programming Language :: Cython",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3 :: Only",
                                "Programming Language :: Python :: 3.10",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.13",
                                "Programming Language :: Python :: 3.9",
                                "Topic :: Scientific/Engineering"
                            ]
                        }
                    ]
                },
                "developer_view": [
                    {
                        "vulnerability_id": "PYSEC-2020-73",
                        "summary": "",
                        "affected_components": [
                            "pandas"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.0.4"
                        ],
                        "impact": "** DISPUTED ** pandas through 1",
                        "remediation_steps": "Upgrade to 1.0.4",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/0FuzzingQ/vuln/blob/master/pandas%20unserialize.md"
                            },
                            {
                                "type": "advisory",
                                "url": "https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_pickle.html"
                            }
                        ]
                    }
                ],
                "tech_leader_view": {
                    "total_vulnerabilities": 1,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 0,
                        "medium": 0,
                        "low": 0
                    }
                }
            },
            "119": {
                "metadata": {
                    "timestamp": "2025-08-27T19:43:01.890352+05:30",
                    "package": "pip",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "pip",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 5 - Production/Stable",
                                "Intended Audience :: Developers",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3 :: Only",
                                "Programming Language :: Python :: 3.10",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.13",
                                "Programming Language :: Python :: 3.14",
                                "Programming Language :: Python :: 3.9",
                                "Programming Language :: Python :: Implementation :: CPython",
                                "Programming Language :: Python :: Implementation :: PyPy",
                                "Topic :: Software Development :: Build Tools"
                            ]
                        }
                    ]
                },
                "developer_view": [
                    {
                        "vulnerability_id": "GHSA-4gv5-qhvr-36vv",
                        "summary": "Improper Link Resolution Before File Access in pip",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.3"
                        ],
                        "impact": "pip before 1",
                        "remediation_steps": "Upgrade to 1.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2013-1888"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/issues/725"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/pull/734/files"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/pull/780/files"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-4gv5-qhvr-36vv"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2013-9.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2013-May/105952.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2013-May/105989.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2013-May/106311.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2013/03/22/10"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-5xp3-jfq3-5q8x",
                        "summary": "Improper Input Validation in pip",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "21.1"
                        ],
                        "impact": "A flaw was found in python-pip in the way it handled Unicode separators in git references",
                        "remediation_steps": "Upgrade to 21.1",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-3572"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/pull/9827"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/commit/e46bdda9711392fec0c45c1175bae6db847cb30b"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2021:3254"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1962856"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-5xp3-jfq3-5q8x"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2021-437.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip"
                            },
                            {
                                "type": "advisory",
                                "url": "https://packetstormsecurity.com/files/162712/USN-4961-1.txt"
                            },
                            {
                                "type": "advisory",
                                "url": "https://security.netapp.com/advisory/ntap-20240621-0006"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpuapr2022.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-c5h8-cq4v-cvfm",
                        "summary": "Improper Authentication in pip",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.5"
                        ],
                        "impact": "The mirroring support (-M, --use-mirrors) in Python Pip before 1",
                        "remediation_steps": "Upgrade to 1.5",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2013-5123"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-5123"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.suse.com/show_bug.cgi?id=CVE-2013-5123"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-c5h8-cq4v-cvfm"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2019-160.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://security-tracker.debian.org/tracker/CVE-2013-5123"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2015-April/155248.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2015-April/155291.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2013/08/21/17"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2013/08/21/18"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-g3p5-fjj9-h8gj",
                        "summary": "Improper Input Validation in pip",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                            "level": "High"
                        },
                        "fixed_versions": [
                            "1.3"
                        ],
                        "impact": "pip before 1",
                        "remediation_steps": "Upgrade to 1.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2013-1629"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/issues/425"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/pull/791/files"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=968059"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-g3p5-fjj9-h8gj"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2013-8.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.pip-installer.org/en/latest/installing.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.pip-installer.org/en/latest/news.html#changelog"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-gpvv-69j7-gwj8",
                        "summary": "Path Traversal in pip",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
                            "level": "High"
                        },
                        "fixed_versions": [
                            "19.2"
                        ],
                        "impact": "The pip package before 19",
                        "remediation_steps": "Upgrade to 19.2",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-20916"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/issues/6413"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-gpvv-69j7-gwj8"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2020-173.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/compare/19.1.1...19.2"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2020/09/msg00010.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpuapr2022.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00005.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00010.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-mq26-g339-26xf",
                        "summary": "Command Injection in pip when used with Mercurial",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "23.3"
                        ],
                        "impact": "When installing a package from a Mercurial VCS URL, e",
                        "remediation_steps": "Upgrade to 23.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-5752"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/pull/12306"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/commit/389cb799d0da9a840749fcd14878928467ed49b4"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2023-228.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ"
                            },
                            {
                                "type": "advisory",
                                "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2013-8",
                        "summary": "",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.3"
                        ],
                        "impact": "pip before 1",
                        "remediation_steps": "Upgrade to 1.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/issues/425"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/pull/791/files"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.pip-installer.org/en/latest/installing.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.pip-installer.org/en/latest/news.html#changelog"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=968059"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-g3p5-fjj9-h8gj"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2013-9",
                        "summary": "",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.3"
                        ],
                        "impact": "pip before 1",
                        "remediation_steps": "Upgrade to 1.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2013/03/22/10"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/pull/734/files"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/issues/725"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/pull/780/files"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2013-May/105952.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2013-May/105989.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2013-May/106311.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-4gv5-qhvr-36vv"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2019-160",
                        "summary": "",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.5"
                        ],
                        "impact": "The mirroring support (-M, --use-mirrors) in Python Pip before 1",
                        "remediation_steps": "Upgrade to 1.5",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2015-April/155248.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2013/08/21/18"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.suse.com/show_bug.cgi?id=CVE-2013-5123"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2015-April/155291.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://security-tracker.debian.org/tracker/CVE-2013-5123"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-5123"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2013/08/21/17"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.securityfocus.com/bid/77520"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-c5h8-cq4v-cvfm"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2020-173",
                        "summary": "",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "a4c735b14a62f9cb864533808ac63936704f2ace"
                        ],
                        "impact": "The pip package before 19",
                        "remediation_steps": "Upgrade to a4c735b14a62f9cb864533808ac63936704f2ace",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/issues/6413"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/compare/19.1.1...19.2"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2020/09/msg00010.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00005.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00010.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-gpvv-69j7-gwj8"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2021-437",
                        "summary": "",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "21.1"
                        ],
                        "impact": "A flaw was found in python-pip in the way it handled Unicode separators in git references",
                        "remediation_steps": "Upgrade to 21.1",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1962856"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-5xp3-jfq3-5q8x"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2023-228",
                        "summary": "",
                        "affected_components": [
                            "pip"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
                            "level": "Low"
                        },
                        "fixed_versions": [
                            "23.3"
                        ],
                        "impact": "When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+",
                        "remediation_steps": "Upgrade to 23.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/pip/pull/12306"
                            }
                        ]
                    }
                ],
                "tech_leader_view": {
                    "total_vulnerabilities": 12,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 2,
                        "medium": 4,
                        "low": 1
                    }
                }
            },
            "120": {
                "metadata": {
                    "timestamp": "2025-08-27T19:43:04.964736+05:30",
                    "package": "python_dateutil",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "python_dateutil",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 5 - Production/Stable",
                                "Intended Audience :: Developers",
                                "License :: OSI Approved :: Apache Software License",
                                "License :: OSI Approved :: BSD License",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 2",
                                "Programming Language :: Python :: 2.7",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3.10",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.3",
                                "Programming Language :: Python :: 3.4",
                                "Programming Language :: Python :: 3.5",
                                "Programming Language :: Python :: 3.6",
                                "Programming Language :: Python :: 3.7",
                                "Programming Language :: Python :: 3.8",
                                "Programming Language :: Python :: 3.9",
                                "Topic :: Software Development :: Libraries"
                            ]
                        }
                    ]
                },
                "developer_view": [],
                "tech_leader_view": {
                    "total_vulnerabilities": 0,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 0,
                        "medium": 0,
                        "low": 0
                    }
                }
            },
            "121": {
                "metadata": {
                    "timestamp": "2025-08-27T19:43:07.777935+05:30",
                    "package": "pytz",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "pytz",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 6 - Mature",
                                "Intended Audience :: Developers",
                                "License :: OSI Approved :: MIT License",
                                "Natural Language :: English",
                                "Operating System :: OS Independent",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 2",
                                "Programming Language :: Python :: 2.4",
                                "Programming Language :: Python :: 2.5",
                                "Programming Language :: Python :: 2.6",
                                "Programming Language :: Python :: 2.7",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3.1",
                                "Programming Language :: Python :: 3.10",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.13",
                                "Programming Language :: Python :: 3.2",
                                "Programming Language :: Python :: 3.3",
                                "Programming Language :: Python :: 3.4",
                                "Programming Language :: Python :: 3.5",
                                "Programming Language :: Python :: 3.6",
                                "Programming Language :: Python :: 3.7",
                                "Programming Language :: Python :: 3.8",
                                "Programming Language :: Python :: 3.9",
                                "Topic :: Software Development :: Libraries :: Python Modules"
                            ]
                        }
                    ]
                },
                "developer_view": [],
                "tech_leader_view": {
                    "total_vulnerabilities": 0,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 0,
                        "medium": 0,
                        "low": 0
                    }
                }
            },
            "122": {
                "metadata": {
                    "timestamp": "2025-08-27T19:43:10.080853+05:30",
                    "package": "requests",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "requests",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 5 - Production/Stable",
                                "Environment :: Web Environment",
                                "Intended Audience :: Developers",
                                "License :: OSI Approved :: Apache Software License",
                                "Natural Language :: English",
                                "Operating System :: OS Independent",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3 :: Only",
                                "Programming Language :: Python :: 3.10",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.13",
                                "Programming Language :: Python :: 3.14",
                                "Programming Language :: Python :: 3.9",
                                "Programming Language :: Python :: Implementation :: CPython",
                                "Programming Language :: Python :: Implementation :: PyPy",
                                "Topic :: Internet :: WWW/HTTP",
                                "Topic :: Software Development :: Libraries"
                            ]
                        }
                    ]
                },
                "developer_view": [
                    {
                        "vulnerability_id": "GHSA-652x-xj99-gmcc",
                        "summary": "Exposure of Sensitive Information to an Unauthorized Actor in Requests",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N",
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "2.3.0"
                        ],
                        "impact": "Requests (aka python-requests) before 2",
                        "remediation_steps": "Upgrade to 2.3.0",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-1830"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/kennethreitz/requests/issues/1885"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/issues/1885"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733108"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2014-14.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://web.archive.org/web/20150523055216/http://www.mandriva.com/en/support/security/advisories/advisory/MDVSA-2015:133/?name=MDVSA-2015:133"
                            },
                            {
                                "type": "advisory",
                                "url": "http://advisories.mageia.org/MGASA-2014-0409.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-updates/2016-01/msg00095.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.debian.org/security/2015/dsa-3146"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2015:133"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-9hjg-9r4m-mvj7",
                        "summary": "Requests vulnerable to .netrc credentials leak via malicious URLs",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "2.32.4"
                        ],
                        "impact": "### Impact\n\nDue to a URL parsing issue, Requests releases prior to 2",
                        "remediation_steps": "Upgrade to 2.32.4",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/security/advisories/GHSA-9hjg-9r4m-mvj7"
                            },
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-47081"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/pull/6965"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/commit/96ba401c1296ab1dda74a2365ef36d88f7d144ef"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests"
                            },
                            {
                                "type": "advisory",
                                "url": "https://requests.readthedocs.io/en/latest/api/#requests.Session.trust_env"
                            },
                            {
                                "type": "advisory",
                                "url": "https://seclists.org/fulldisclosure/2025/Jun/2"
                            },
                            {
                                "type": "advisory",
                                "url": "http://seclists.org/fulldisclosure/2025/Jun/2"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2025/06/03/11"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2025/06/03/9"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2025/06/04/1"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2025/06/04/6"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-9wx4-h78v-vm56",
                        "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "2.32.0"
                        ],
                        "impact": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`",
                        "remediation_steps": "Upgrade to 2.32.0",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                            },
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/pull/6655"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-cfj3-7x9c-4p3h",
                        "summary": "Exposure of Sensitive Information to an Unauthorized Actor in Requests",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "2.3.0"
                        ],
                        "impact": "Requests (aka python-requests) before 2",
                        "remediation_steps": "Upgrade to 2.3.0",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-1829"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/kennethreitz/requests/issues/1885"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/issues/1885"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733108"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-cfj3-7x9c-4p3h"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2014-13.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://web.archive.org/web/20150523055216/http://www.mandriva.com/en/support/security/advisories/advisory/MDVSA-2015:133/?name=MDVSA-2015:133"
                            },
                            {
                                "type": "advisory",
                                "url": "http://advisories.mageia.org/MGASA-2014-0409.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.debian.org/security/2015/dsa-3146"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2015:133"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.ubuntu.com/usn/USN-2382-1"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-x84v-xcm2-53pg",
                        "summary": "Insufficiently Protected Credentials in Requests",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                            "level": "High"
                        },
                        "fixed_versions": [
                            "2.20.0"
                        ],
                        "impact": "The Requests package through 2",
                        "remediation_steps": "Upgrade to 2.20.0",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-18074"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/requests/requests/issues/4716"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/requests/requests/pull/4718"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:2035"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/910766"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2018-28.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/requests/requests"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3790-1"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3790-2"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://docs.python-requests.org/en/master/community/updates/#release-and-version-history"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2014-13",
                        "summary": "",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "2.3.0"
                        ],
                        "impact": "Requests (aka python-requests) before 2",
                        "remediation_steps": "Upgrade to 2.3.0",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733108"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/kennethreitz/requests/issues/1885"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.ubuntu.com/usn/USN-2382-1"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.debian.org/security/2015/dsa-3146"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2015:133"
                            },
                            {
                                "type": "advisory",
                                "url": "http://advisories.mageia.org/MGASA-2014-0409.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-cfj3-7x9c-4p3h"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2014-14",
                        "summary": "",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "2.3.0"
                        ],
                        "impact": "Requests (aka python-requests) before 2",
                        "remediation_steps": "Upgrade to 2.3.0",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/kennethreitz/requests/issues/1885"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=733108"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.debian.org/security/2015/dsa-3146"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2015:133"
                            },
                            {
                                "type": "advisory",
                                "url": "http://advisories.mageia.org/MGASA-2014-0409.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-updates/2016-01/msg00095.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-652x-xj99-gmcc"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2015-17",
                        "summary": "",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "3bd8afbff29e50b38f889b2f688785a669b9aafc"
                        ],
                        "impact": "The resolve_redirects function in sessions",
                        "remediation_steps": "Upgrade to 3bd8afbff29e50b38f889b2f688785a669b9aafc",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2015/03/15/1"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.ubuntu.com/usn/USN-2531-1"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2015/03/14/4"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/kennethreitz/requests/commit/3bd8afbff29e50b38f889b2f688785a669b9aafc"
                            },
                            {
                                "type": "advisory",
                                "url": "https://warehouse.python.org/project/requests/2.6.0/"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.fedoraproject.org/pipermail/package-announce/2015-March/153594.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://advisories.mageia.org/MGASA-2015-0120.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2015:133"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2018-28",
                        "summary": "",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "c45d7c49ea75133e52ab22a8e9e13173938e36ff"
                        ],
                        "impact": "The Requests package before 2",
                        "remediation_steps": "Upgrade to c45d7c49ea75133e52ab22a8e9e13173938e36ff",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/requests/requests/pull/4718"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/requests/requests/issues/4716"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.debian.org/910766"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3790-1/"
                            },
                            {
                                "type": "advisory",
                                "url": "http://docs.python-requests.org/en/master/community/updates/#release-and-version-history"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3790-2/"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:2035"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-x84v-xcm2-53pg"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2023-74",
                        "summary": "",
                        "affected_components": [
                            "requests"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
                        ],
                        "impact": "Requests is a HTTP library",
                        "remediation_steps": "Upgrade to 74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/releases/tag/v2.31.0"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/"
                            }
                        ]
                    }
                ],
                "tech_leader_view": {
                    "total_vulnerabilities": 10,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 1,
                        "medium": 3,
                        "low": 0
                    }
                }
            },
            "123": {
                "metadata": {
                    "timestamp": "2025-08-27T19:43:13.418374+05:30",
                    "package": "six",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "six",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 5 - Production/Stable",
                                "Intended Audience :: Developers",
                                "License :: OSI Approved :: MIT License",
                                "Programming Language :: Python :: 2",
                                "Programming Language :: Python :: 3",
                                "Topic :: Software Development :: Libraries",
                                "Topic :: Utilities"
                            ]
                        }
                    ]
                },
                "developer_view": [],
                "tech_leader_view": {
                    "total_vulnerabilities": 0,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 0,
                        "medium": 0,
                        "low": 0
                    }
                }
            },
            "124": {
                "metadata": {
                    "timestamp": "2025-08-27T19:43:15.049472+05:30",
                    "package": "tzdata",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "tzdata",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Development Status :: 4 - Beta",
                                "Intended Audience :: Developers",
                                "License :: OSI Approved :: Apache Software License",
                                "Programming Language :: Python :: 2",
                                "Programming Language :: Python :: 3"
                            ]
                        }
                    ]
                },
                "developer_view": [],
                "tech_leader_view": {
                    "total_vulnerabilities": 0,
                    "severity_breakdown": {
                        "critical": 0,
                        "high": 0,
                        "medium": 0,
                        "low": 0
                    }
                }
            },
            "125": {
                "metadata": {
                    "timestamp": "2025-08-27T19:43:17.405452+05:30",
                    "package": "urllib3",
                    "version": "latest",
                    "ecosystem": "PyPI",
                    "index_insights": [
                        {
                            "source": "PyPI",
                            "package": "urllib3",
                            "version": "latest",
                            "deprecated": false,
                            "yanked": false,
                            "eol": false,
                            "classifiers": [
                                "Environment :: Web Environment",
                                "Intended Audience :: Developers",
                                "Operating System :: OS Independent",
                                "Programming Language :: Python",
                                "Programming Language :: Python :: 3",
                                "Programming Language :: Python :: 3 :: Only",
                                "Programming Language :: Python :: 3.10",
                                "Programming Language :: Python :: 3.11",
                                "Programming Language :: Python :: 3.12",
                                "Programming Language :: Python :: 3.13",
                                "Programming Language :: Python :: 3.9",
                                "Programming Language :: Python :: Implementation :: CPython",
                                "Programming Language :: Python :: Implementation :: PyPy",
                                "Topic :: Internet :: WWW/HTTP",
                                "Topic :: Software Development :: Libraries"
                            ]
                        }
                    ]
                },
                "developer_view": [
                    {
                        "vulnerability_id": "GHSA-34jh-p97f-mpxf",
                        "summary": "urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.26.19"
                        ],
                        "impact": "When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected",
                        "remediation_steps": "Upgrade to 1.26.19",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"
                            },
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37891"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-g4mx-q9vg-27p4",
                        "summary": "urllib3's request body not stripped after redirect from 303 status changes request method to GET",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "2.0.7"
                        ],
                        "impact": "urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 303 \"See Other\" after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs",
                        "remediation_steps": "Upgrade to 2.0.7",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
                            },
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-45803"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/4e50fbc5db74e32cabd5ccc1ab81fc103adfe0b3"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/b594c5ceaca38e1ac215f916538fb128e3526a36"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-212.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/releases/tag/1.26.18"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/releases/tag/2.0.7"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-gwvm-45gx-3cf8",
                        "summary": "Authorization Header forwarded on redirect",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.24.2"
                        ],
                        "impact": "urllib3 before 1",
                        "remediation_steps": "Upgrade to 1.24.2",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-25091"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/issues/1510"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/adb358f8e06865406d1f05e581a16cbea2136fbc"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-207.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/compare/1.24.1...1.24.2"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-mh33-7rrq-662w",
                        "summary": "Improper Certificate Validation in urllib3",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
                            "level": "High"
                        },
                        "fixed_versions": [
                            "1.24.2"
                        ],
                        "impact": "The urllib3 library before 1",
                        "remediation_steps": "Upgrade to 1.24.2",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-11324"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/1efadf43dc63317cd9eaa3e0fdb9e05ab07254b1"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3590"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-mh33-7rrq-662w"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2019-133.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2"
                            },
                            {
                                "type": "advisory",
                                "url": "https://pypi.org/project/urllib3/1.24.2"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3990-1"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2019/04/19/1"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-pq67-6m6q-mj2v",
                        "summary": "urllib3 redirects are not disabled when retries are disabled on PoolManager instantiation",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "2.5.0"
                        ],
                        "impact": "urllib3 handles redirects and retries using the same mechanism, which is controlled by the `Retry` object",
                        "remediation_steps": "Upgrade to 2.5.0",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-pq67-6m6q-mj2v"
                            },
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-50181"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/f05b1329126d5be6de501f9d1e3e36738bc08857"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-r64q-w8jr-g9qp",
                        "summary": "Improper Neutralization of CRLF Sequences in urllib3 library for Python",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.24.3"
                        ],
                        "impact": "In the urllib3 library through 1",
                        "remediation_steps": "Upgrade to 1.24.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-11236"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/issues/1553"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3990-2"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3990-1"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TBI45HO533KYHNB5YRO43TBYKA3E3VRL"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/R62XGEYPUTXMRHGX5I37EBCGQ5COHGKR"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00016.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2019-132.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-r64q-w8jr-g9qp"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3590"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:2272"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-v845-jxx5-vc9f",
                        "summary": "`Cookie` HTTP header isn't stripped on cross-origin redirects",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "2.0.6"
                        ],
                        "impact": "urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user",
                        "remediation_steps": "Upgrade to 2.0.6",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"
                            },
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-43804"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-192.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ"
                            },
                            {
                                "type": "advisory",
                                "url": "https://security.netapp.com/advisory/ntap-20241213-0007"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.vicarius.io/vsociety/posts/cve-2023-43804-urllib3-vulnerability-3"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-wqvq-5m8c-6g24",
                        "summary": "CRLF injection in urllib3",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "1.25.9"
                        ],
                        "impact": "urllib3 before 1",
                        "remediation_steps": "Upgrade to 1.25.9",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-26137"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/pull/1800"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugs.python.org/issue39603"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2020-148.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/4570-1"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.oracle.com/security-alerts/cpuoct2021.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "GHSA-www2-v7xj-xrc6",
                        "summary": "Exposure of Sensitive Information to an Unauthorized Actor in urllib3",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                            "level": "Critical"
                        },
                        "fixed_versions": [
                            "1.23"
                        ],
                        "impact": "urllib3 before version 1",
                        "remediation_steps": "Upgrade to 1.23",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-20060"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/issues/1316"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/pull/1346"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/560bd227b90f74417ffaedebf5f8d05a8ee4f532"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3990-1"
                            },
                            {
                                "type": "advisory",
                                "url": "https://security.netapp.com/advisory/ntap-20241227-0010"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XWP36YW3KSVLXDBY3QJKDYEPCIMN3VQZ"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BXLAXHM3Z6DUCXZ7ZXZ2EAYJXWDCZFCT"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5SJERZEJDSUYQP7BNBXMBHRHGY26HRZD"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWP36YW3KSVLXDBY3QJKDYEPCIMN3VQZ"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BXLAXHM3Z6DUCXZ7ZXZ2EAYJXWDCZFCT"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5SJERZEJDSUYQP7BNBXMBHRHGY26HRZD"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/blob/master/CHANGES.rst"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2018-32.yaml"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1649153"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:2272"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2018-32",
                        "summary": "",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.23"
                        ],
                        "impact": "urllib3 before version 1",
                        "remediation_steps": "Upgrade to 1.23",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/pull/1346"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/issues/1316"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/blob/master/CHANGES.rst"
                            },
                            {
                                "type": "advisory",
                                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1649153"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5SJERZEJDSUYQP7BNBXMBHRHGY26HRZD/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XWP36YW3KSVLXDBY3QJKDYEPCIMN3VQZ/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BXLAXHM3Z6DUCXZ7ZXZ2EAYJXWDCZFCT/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3990-1/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:2272"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-www2-v7xj-xrc6"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2019-132",
                        "summary": "",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.24.3"
                        ],
                        "impact": "In the urllib3 library through 1",
                        "remediation_steps": "Upgrade to 1.24.3",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/issues/1553"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3990-1/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TBI45HO533KYHNB5YRO43TBYKA3E3VRL/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/R62XGEYPUTXMRHGX5I37EBCGQ5COHGKR/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00016.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3990-2/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:2272"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3590"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-r64q-w8jr-g9qp"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2019-133",
                        "summary": "",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1.24.2"
                        ],
                        "impact": "The urllib3 library before 1",
                        "remediation_steps": "Upgrade to 1.24.2",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4"
                            },
                            {
                                "type": "advisory",
                                "url": "http://www.openwall.com/lists/oss-security/2019/04/19/1"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/3990-1/"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html"
                            },
                            {
                                "type": "advisory",
                                "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                            },
                            {
                                "type": "advisory",
                                "url": "https://access.redhat.com/errata/RHSA-2019:3590"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-mh33-7rrq-662w"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2020-148",
                        "summary": "",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "1dd69c5c5982fae7c87a620d487c2ebf7a6b436b"
                        ],
                        "impact": "urllib3 before 1",
                        "remediation_steps": "Upgrade to 1dd69c5c5982fae7c87a620d487c2ebf7a6b436b",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://bugs.python.org/issue39603"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/pull/1800"
                            },
                            {
                                "type": "advisory",
                                "url": "https://usn.ubuntu.com/4570-1/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-wqvq-5m8c-6g24"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2021-108",
                        "summary": "",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "2d4a3fee6de2fa45eb82169361918f759269b4ec"
                        ],
                        "impact": "An issue was discovered in urllib3 before 1",
                        "remediation_steps": "Upgrade to 2d4a3fee6de2fa45eb82169361918f759269b4ec",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/advisories/GHSA-q2q7-5pp4-w6pg"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2021-59",
                        "summary": "",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "Unknown",
                            "score": null,
                            "level": "Unknown"
                        },
                        "fixed_versions": [
                            "8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0"
                        ],
                        "impact": "The urllib3 library 1",
                        "remediation_steps": "Upgrade to 8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commits/main"
                            },
                            {
                                "type": "advisory",
                                "url": "https://pypi.org/project/urllib3/1.26.4/"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2023-192",
                        "summary": "",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
                            "level": "High"
                        },
                        "fixed_versions": [
                            "01220354d389cd05474713f8c982d05c9b17aafb"
                        ],
                        "impact": "urllib3 is a user-friendly HTTP client library for Python",
                        "remediation_steps": "Upgrade to 01220354d389cd05474713f8c982d05c9b17aafb",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2023-207",
                        "summary": "",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "adb358f8e06865406d1f05e581a16cbea2136fbc"
                        ],
                        "impact": "urllib3 before 1",
                        "remediation_steps": "Upgrade to adb358f8e06865406d1f05e581a16cbea2136fbc",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/compare/1.24.1...1.24.2"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/issues/1510"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/adb358f8e06865406d1f05e581a16cbea2136fbc"
                            }
                        ]
                    },
                    {
                        "vulnerability_id": "PYSEC-2023-212",
                        "summary": "",
                        "affected_components": [
                            "urllib3"
                        ],
                        "severity": {
                            "type": "CVSS_V3",
                            "score": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                            "level": "Medium"
                        },
                        "fixed_versions": [
                            "4e98d57809dacab1cbe625fddeec1a290c478ea9"
                        ],
                        "impact": "urllib3 is a user-friendly HTTP client library for Python",
                        "remediation_steps": "Upgrade to 4e98d57809dacab1cbe625fddeec1a290c478ea9",
                        "references": [
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
                            },
                            {
                                "type": "advisory",
                                "url": "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
                            },
                            {
                                "type": "advisory",
                                "url": "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"
                            },
                            {
                                "type": "advisory",
                                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/"
                            }
                        ]
                    }
                ],
                "tech_leader_view": {
                    "total_vulnerabilities": 18,
                    "severity_breakdown": {
                        "critical": 1,
                        "high": 2,
                        "medium": 9,
                        "low": 0
                    }
                }
            }
        }
    ]
}